### PR TITLE
Update plugin.py

### PR DESCRIPTION
**Pull request by Gustus26**
Openatv 7.1 crashlog opening eventviews

File "/usr/lib/enigma2/python/Plugins/Extensions/EPGTranslator/plugin.py", line 1119, in My_setEvent
AttributeError: 'EventViewEPGSelect' object has no attribute 'currentService'
[ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xa5d31cb8>>,('EPGSelectActions', 'info')) failed)

changed

Line 1119:     uref = make_uref(event.getEventId(), self.currentService.getServiceName())
to
Line 1119:     uref = make_uref(event.getEventId(), self.serviceRef.getServiceName())

### CODE REVIEW

**Comment by Huevos** [comment]
This needs to be checked in OpenViX.

**Comment by Gustus26** [comment]
I can confirm it works in openvix 

You are correct self.currentService  is missing from the eventview in openatv 7.1and using self.serviceRef works in openatv 6.4 and 7.1 and openvix 6 and should work in every image. Unless you have a better work around?

**Comment by original-birdman** [comment]
This proposed change does **NOT** work on OpenVix 6.0.009.002.
```
<   363.1806> Traceback (most recent call last):
<   363.1808>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 60, in action
<   363.1829>   File "/usr/lib/enigma2/python/Plugins/Extensions/EPGTranslator/plugin.py", line 1085, in EPGTr_ToggleMode
<   363.1876>     self.setEvent(self.event)
<   363.1878>   File "/usr/lib/enigma2/python/Plugins/Extensions/EPGTranslator/plugin.py", line 1120, in My_setEvent
<   363.1927>     uref = make_uref(event.getEventId(), self.serviceRef.getServiceName())
<   363.1931> AttributeError: 'EventViewEPGSelect' object has no attribute 'serviceRef'
```

**Comment by Gustus26** [comment]
My intention was to fix the openatv 7.1 crash and it worked. It clear now that my testing openvix image didnt show any errors until a clean image install. Please except my apologies it was not my intention to break anything. I will try and find a work around and post back. The best is to revert back to the orignal code and i will you my fix for openatv 7.1

**Comment by original-birdman** [comment]
The problem will _only_ be seen in an EventView window (so, on Vix at least, press `Info` to get a description of the current service popped up, then press `Text` to get a translation).

The EPGTranslator's EPG browser isn't affected and should continue to work.

**Comment by Gustus26** [comment]
Yes its only in EventView windows and clear my first testing didnt find a error.  
openvix is self.currentService = ref 
openatv 7.1 = self.serviceRef = serviceRef
