### ISSUE TITLE
EPGTranslator not working with OpenATV 7.2

### ISSUE THREAD

**Issue by falconHorizon52** [oe-alliance/oe-alliance-plugins#670]
When called it with view event it crash with this error
19:39:06.2625   File "/usr/lib/enigma2/python/Plugins/Extensions/EPGTranslator/plugin.py", line 1119, in My_setEvent
19:39:06.2632 AttributeError: 'EventViewEPGSelect' object has no attribute 'currentService'
19:39:06.2633 [ePyObject] (PyObject_CallObject(<bound method HelpableButtonSetupActionMap.action of <Screens.ButtonSetup.HelpableButtonSetupActionMap object at 0xacf3ebb0>>,('ButtonSetupActions', 'red')) failed) #

currentService attribute need to replaced with serviceRef to start work again normaly

line 1119 uref = make_uref(event.getEventId(), self.currentService.getServiceName())
to uref = make_uref(event.getEventId(), self.serviceRef.getServiceName())

#671
